trial to run sta without hardening

diff --git a/.github/workflows/user_project_ci.yml b/.github/workflows/user_project_ci.yml
--- a/.github/workflows/user_project_ci.yml
+++ b/.github/workflows/user_project_ci.yml
@@ -62,113 +62,113 @@ jobs:
           name: ${{ matrix.designs }}-tarball
           path: /tmp/${{ matrix.designs }}.tar
   
-  harden_designs:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        pdk: ["sky130A", "sky130B"]
-        designs: ["caravel_user_project"]
-    needs: [setup_env, download_designs]
-    steps:
-      - uses: actions/checkout@v3
+  # harden_designs:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       pdk: ["sky130A", "sky130B"]
+  #       designs: ["caravel_user_project"]
+  #   needs: [setup_env, download_designs]
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v1
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
 
-      - name: Export Environment Variables
-        run: |
-          echo "CARAVEL_ROOT=/home/runner/work/dependencies/caravel" >> $GITHUB_ENV
-          echo "MCW_ROOT=/home/runner/work/dependencies/caravel_mgmt_soc_litex" >> $GITHUB_ENV
-          echo "PRECHECK_ROOT=/home/runner/work/dependencies/mpw_precheck" >> $GITHUB_ENV
-          echo "PDK_ROOT=/home/runner/work/dependencies/pdk/pdk" >> $GITHUB_ENV
-          echo "OPENLANE_ROOT=/home/runner/work/dependencies/OpenLane" >> $GITHUB_ENV
-          echo "PDK=${{ matrix.pdk }}" >> $GITHUB_ENV
-          echo "DEPENDENCIES_PATH=/home/runner/work/dependencies" >> $GITHUB_ENV
-          echo "DESIGN_PATH=/home/runner/work/designs/${{ matrix.designs }}" >> $GITHUB_ENV
+  #     - name: Export Environment Variables
+  #       run: |
+  #         echo "CARAVEL_ROOT=/home/runner/work/dependencies/caravel" >> $GITHUB_ENV
+  #         echo "MCW_ROOT=/home/runner/work/dependencies/caravel_mgmt_soc_litex" >> $GITHUB_ENV
+  #         echo "PRECHECK_ROOT=/home/runner/work/dependencies/mpw_precheck" >> $GITHUB_ENV
+  #         echo "PDK_ROOT=/home/runner/work/dependencies/pdk/pdk" >> $GITHUB_ENV
+  #         echo "OPENLANE_ROOT=/home/runner/work/dependencies/OpenLane" >> $GITHUB_ENV
+  #         echo "PDK=${{ matrix.pdk }}" >> $GITHUB_ENV
+  #         echo "DEPENDENCIES_PATH=/home/runner/work/dependencies" >> $GITHUB_ENV
+  #         echo "DESIGN_PATH=/home/runner/work/designs/${{ matrix.designs }}" >> $GITHUB_ENV
 
-      - name: Download OpenLane Tarball
-        uses: actions/download-artifact@v3
-        with:
-          name: OpenLane-tarball
-          path: /tmp
+  #     - name: Download OpenLane Tarball
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: OpenLane-tarball
+  #         path: /tmp
 
-      - name: Unpack OpenLane Tarball
-        run: |
-          sudo mkdir -p ${{ env.DEPENDENCIES_PATH }}/OpenLane
-          sudo chown -R $USER:$USER ${{ env.DEPENDENCIES_PATH }}/OpenLane
-          tar -xf /tmp/OpenLane.tar -C ${{ env.DEPENDENCIES_PATH }}/OpenLane .\
+  #     - name: Unpack OpenLane Tarball
+  #       run: |
+  #         sudo mkdir -p ${{ env.DEPENDENCIES_PATH }}/OpenLane
+  #         sudo chown -R $USER:$USER ${{ env.DEPENDENCIES_PATH }}/OpenLane
+  #         tar -xf /tmp/OpenLane.tar -C ${{ env.DEPENDENCIES_PATH }}/OpenLane .\
 
-      - name: Download pdk Tarball
-        uses: actions/download-artifact@v3
-        with:
-          name: pdk-tarball
-          path: /tmp
+  #     - name: Download pdk Tarball
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: pdk-tarball
+  #         path: /tmp
 
-      - name: Unpack pdk Tarball
-        run: |
-          sudo mkdir -p ${{ env.DEPENDENCIES_PATH }}/pdk
-          sudo chown -R $USER:$USER ${{ env.DEPENDENCIES_PATH }}/pdk
-          tar -xf /tmp/pdk.tar -C ${{ env.DEPENDENCIES_PATH }}/pdk .
+  #     - name: Unpack pdk Tarball
+  #       run: |
+  #         sudo mkdir -p ${{ env.DEPENDENCIES_PATH }}/pdk
+  #         sudo chown -R $USER:$USER ${{ env.DEPENDENCIES_PATH }}/pdk
+  #         tar -xf /tmp/pdk.tar -C ${{ env.DEPENDENCIES_PATH }}/pdk .
 
-      - name: Download ${{ matrix.designs }} Tarball
-        uses: actions/download-artifact@v3
-        with:
-          name: ${{ matrix.designs }}-tarball
-          path: /tmp
+  #     - name: Download ${{ matrix.designs }} Tarball
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: ${{ matrix.designs }}-tarball
+  #         path: /tmp
 
-      - name: Unpack ${{ matrix.designs }} Tarball
-        run: |
-          sudo mkdir -p ${{ env.DESIGN_PATH }}
-          sudo chown -R $USER:$USER ${{ env.DESIGN_PATH }}
-          tar -xf /tmp/${{ matrix.designs }}.tar -C ${{ env.DESIGN_PATH }} .
+  #     - name: Unpack ${{ matrix.designs }} Tarball
+  #       run: |
+  #         sudo mkdir -p ${{ env.DESIGN_PATH }}
+  #         sudo chown -R $USER:$USER ${{ env.DESIGN_PATH }}
+  #         tar -xf /tmp/${{ matrix.designs }}.tar -C ${{ env.DESIGN_PATH }} .
 
-      - name: setup openlane
-        run: |
-          json_file=$(cat $GITHUB_WORKSPACE/tools.json)
-          openlane_commit=$(echo "${json_file}" | jq -r ".OpenLane.commit")
-          export OPENLANE_IMAGE_NAME=efabless/openlane:${openlane_commit}
-          export IMAGE_NAME=efabless/openlane:${openlane_commit}
-          echo "OPENLANE_IMAGE_NAME=efabless/openlane:${openlane_commit}" >> $GITHUB_ENV
-          echo "IMAGE_NAME=efabless/openlane:${openlane_commit}" >> $GITHUB_ENV
-          cd ${{ env.OPENLANE_ROOT }}
-          make pull-openlane
+  #     - name: setup openlane
+  #       run: |
+  #         json_file=$(cat $GITHUB_WORKSPACE/tools.json)
+  #         openlane_commit=$(echo "${json_file}" | jq -r ".OpenLane.commit")
+  #         export OPENLANE_IMAGE_NAME=efabless/openlane:${openlane_commit}
+  #         export IMAGE_NAME=efabless/openlane:${openlane_commit}
+  #         echo "OPENLANE_IMAGE_NAME=efabless/openlane:${openlane_commit}" >> $GITHUB_ENV
+  #         echo "IMAGE_NAME=efabless/openlane:${openlane_commit}" >> $GITHUB_ENV
+  #         cd ${{ env.OPENLANE_ROOT }}
+  #         make pull-openlane
 
 
-      - name: harden
-        run: |
-          ls ${{ env.PDK_ROOT }}
-          cd ${{ env.DESIGN_PATH }}/${{ matrix.designs }}
-          python3 $GITHUB_WORKSPACE/.github/scripts/get_designs.py --design ${{ env.DESIGN_PATH }}/${{ matrix.designs }}
-          for word in $(cat harden_sequence.txt); do
-            make $word
-          done
+  #     - name: harden
+  #       run: |
+  #         ls ${{ env.PDK_ROOT }}
+  #         cd ${{ env.DESIGN_PATH }}/${{ matrix.designs }}
+  #         python3 $GITHUB_WORKSPACE/.github/scripts/get_designs.py --design ${{ env.DESIGN_PATH }}/${{ matrix.designs }}
+  #         for word in $(cat harden_sequence.txt); do
+  #           make $word
+  #         done
       
-      - name: upload failure logs
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: error
-          path: |
-            /home/runner/work/${{ env.DESIGN_PATH }}/openlane/*/runs
+  #     - name: upload failure logs
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: error
+  #         path: |
+  #           /home/runner/work/${{ env.DESIGN_PATH }}/openlane/*/runs
 
-      - name: cleanup
-        run: |
-          cd ${{ env.DESIGN_PATH }}/${{ matrix.designs }}
-          rm -rf openlane/*/runs
+  #     - name: cleanup
+  #       run: |
+  #         cd ${{ env.DESIGN_PATH }}/${{ matrix.designs }}
+  #         rm -rf openlane/*/runs
 
-      - name: Tarball Designs
-        run: |
-          tar -cf /tmp/${{ matrix.designs }}.tar -C $DESIGN_PATH .
+  #     - name: Tarball Designs
+  #       run: |
+  #         tar -cf /tmp/${{ matrix.designs }}.tar -C $DESIGN_PATH .
 
-      - name: Upload ${{ matrix.designs }} Tarball
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ matrix.designs }}-tarball
-          path: /tmp/${{ matrix.designs }}.tar
+  #     - name: Upload ${{ matrix.designs }} Tarball
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ matrix.designs }}-tarball
+  #         path: /tmp/${{ matrix.designs }}.tar
   
   run_precheck:
     runs-on: ubuntu-latest
@@ -177,7 +177,7 @@ jobs:
       matrix:
         pdk: ["sky130A", "sky130B"]
         designs: ["caravel_user_project"]
-    needs: [harden_designs]
+    needs: [setup_env, download_designs]
     steps:
       - uses: actions/checkout@v3
 
@@ -259,7 +259,7 @@ jobs:
       matrix:
         pdk: ["sky130A", "sky130B"]
         designs: ["caravel_user_project"]
-    needs: [harden_designs]
+    needs: [setup_env, download_designs]
     steps:
       - uses: actions/checkout@v3
 
@@ -280,8 +280,8 @@ jobs:
           echo "PDK=${{ matrix.pdk }}" >> $GITHUB_ENV
           echo "DEPENDENCIES_PATH=/home/runner/work/dependencies" >> $GITHUB_ENV
           echo "DESIGN_PATH=/home/runner/work/designs/${{ matrix.designs }}" >> $GITHUB_ENV
-          echo "CUP_ROOT=/home/runner/work/designs/${{ matrix.designs }}" >> $GITHUB_ENV
-          echo "PROJECT_ROOT=/home/runner/work/designs/${{ matrix.designs }}" >> $GITHUB_ENV
+          echo "CUP_ROOT=${{ env.DESIGN_PATH }}/${{ matrix.designs }}" >> $GITHUB_ENV
+          echo "PROJECT_ROOT=${{ env.DESIGN_PATH }}/${{ matrix.designs }}" >> $GITHUB_ENV
 
       - name: Download pdk Tarball
         uses: actions/download-artifact@v3
@@ -345,12 +345,12 @@ jobs:
 
       - name: run sta
         run: |
-          cd ${{ env.DESIGN_PATH }}
+          cd ${{ env.CUP_ROOT }}
           make extract-parasitics
           make create-spef-mapping
           make caravel-sta
-          tar -cf /tmp/timing.tar ${{ env.DESIGN_PATH }}/signoff/caravel/openlane-signoff/timing
-          vio=$(grep -c "vio(" ${{ env.DESIGN_PATH }}/signoff/caravel/openlane-signoff/timing/all-summary.rpt || true)
+          tar -cf /tmp/timing.tar ${{ env.CUP_ROOT }}/signoff/caravel/openlane-signoff/timing
+          vio=$(grep -c "vio(" ${{ env.CUP_ROOT }}/signoff/caravel/openlane-signoff/timing/all-summary.rpt || true)
           if [[ $vio -gt 0 ]];
           then 
             echo "STA violation count: $vio"
